Add packaging module to Cantera build dependencies
Cantera's SConstruct requires the packaging module:
  ModuleNotFoundError: No module named 'packaging'
  File "SConstruct", line 90: from packaging.specifiers import SpecifierSet

Added packaging to pip install for Cantera build dependencies.